[versions]
kotest = "6.1.0"
kotlin = "2.3.0"
ktlint = "1.8.0"

[libraries]
android-plugin-gradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-plugin-gradle = "com.android.tools.build:gradle:8.13.2"
compose-foundation-foundation = "androidx.compose.foundation:foundation:1.10.1"
kotest-runner = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }
kotest-property = { module = "io.kotest:kotest-property", version.ref = "kotest" }

[plugins]
nexus-publish = { id = "io.github.gradle-nexus.publish-plugin", version = "2.0.0" }
spotless = { id = "com.diffplug.spotless", version = "8.1.0" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }