[versions]
kotest = "6.0.5"
kotlin = "2.2.21"
ktlint = "0.50.0"

[libraries]
android-plugin-gradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-plugin-gradle = "com.android.tools.build:gradle:8.13.1"
compose-foundation-foundation = "androidx.compose.foundation:foundation:1.9.5"
kotest-runner = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }
kotest-property = { module = "io.kotest:kotest-property", version.ref = "kotest" }

[plugins]
nexus-publish = { id = "io.github.gradle-nexus.publish-plugin", version = "2.0.0" }
spotless = { id = "com.diffplug.spotless", version = "8.0.0" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }